title: 'Knowledge '
description: 'Every day learning '
template:
  repo: knowledge-template
  name: knowledge
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
